In [2]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)
x.grad

在计算y关于x的梯度之前需要一个地方存储梯度 此处等价于x=torch.arange(4.0,requires_grad_=True)

In [4]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()#利用反向传播函数来自动计算y关于x的每个分量的梯度
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad==4*x

tensor([True, True, True, True])

In [7]:
#默认情况下，pytorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [8]:
#对于非标量调用backward需要传入一个gradient参数，指定微分函数
x.grad.zero_()
y=x*x
#等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [9]:
#把一些计算移动到记录的计算图之外
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x

z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [10]:
def f(a):
    b=a*2
    while b.norm() < 1000:
        b=b*2
    if b.sum() > 0:
        c=b;
    else:
        c=100*b
    return c

a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()

a.grad==d/a

tensor(True)