In [17]:
import torch
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
x.shape

torch.Size([12])

In [19]:
x.numel()#number of elements


12

In [20]:
# 改变一个张量的形状而不改变元素数量和元素值
x=x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [21]:
# 用0填充一个两行且每行是三行四列的矩阵
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
torch.tensor([[2,1,3,4],[1,2,3,4],[6,7,5,6]])

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [6, 7, 5, 6]])

In [23]:
x=torch.tensor([1.0,2.0,4.0,8.0])
y=torch.Tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [24]:
torch.exp(x)


tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [25]:
x=torch.arange(12,dtype=torch.float32).reshape((3,4))
y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
# 按第0维合并即按行合并,按第1维合并即按列合并
torch.cat((x,y),dim=0) ,torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [26]:
# 通过逻辑运算符构建二元张量
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
x.sum()

tensor(66.)

In [28]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b 

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [29]:
# 会通过广播机制 将少的那个做复制来完成相加
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [30]:
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [31]:
# 该操作会为新结果分配内存
before =id(y)
y =y+x
id(y)==before

False

In [32]:
# 执行原地操作
z=torch.zeros_like(y)
print('id(z):',id(z))
z[:]=x+y
print('id(z):',id(z))

id(z): 1140831567744
id(z): 1140831567744
