实现汇聚层的正向传播

In [2]:
import torch
from torch import nn
from d2l import torch as d2l

def pool2d(X,pool_size,mode='max'):
    p_h,p_w=pool_size
    Y=torch.zeros((X.shape[0]-p_h+1,X.shape[1]-p_w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode =='max':
                Y[i,j]=X[i:i+p_h,j:j+p_w].max()
            if mode =='avg':
                Y[i,j]=X[i:i+p_h,j:j+p_w].mean()
    return Y

In [5]:
X=torch.tensor([[0.0,1.0,2.0],[3.0,4.0,5.0],[6.0,7.0,8.0]])
Y=pool2d(X,(2,2))
Y

tensor([[4., 5.],
        [7., 8.]])

In [7]:
#此外我们还可以验证平均汇聚层
Y=pool2d(X,(2,2),'avg')
Y

tensor([[2., 3.],
        [5., 6.]])

# 填充和步幅
与卷积层一样，汇聚层也可以改变输出形状。和以前一样，我们可以通过填充和步幅以获得所需的输出形状。 下面，我们用深度学习框架中内置的二维最大汇聚层，来演示汇聚层中填充和步幅的使用。 我们首先构造了一个输入张量 X，它有四个维度，其中样本数和通道数都是 1。

In [8]:
X=torch.arange(16,dtype=d2l.float32).reshape(shape=(1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [10]:
#默认情况下，深度学习框架中的步幅与池化窗口的大小相同。 
# 因此，如果我们使用形状为 (3, 3) 的池化窗口，
# 那么默认情况下，我们得到的步幅形状为 (3, 3)。
pool2d=nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [11]:
#填充和步幅可以手动设定
pool2d=nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [20]:
#当然我们可以设置任意大小的矩形池化窗口，并且分别设定填充和步幅的高度宽度
pool2d=nn.MaxPool2d((2,3),padding=(1,1),stride=(2,3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]],

         [[ 2.,  4.],
          [10., 12.],
          [14., 16.]]]])

多个通道的情况

In [19]:
X=torch.cat((X,X+1),1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [21]:
pool2d=nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])